index.html

new font in aj's section

---

README.md

Add Travis Mowers

---

README.md

Made change to Add Natalie Galucia name to .README

Add Natalie Galucia

---

README.md

My name added

---

index.html

Please add my pic and info to the student project.
Thanks!

Add Travis pic and info

---

index.html

Add Natalie Info to index.html

---

css/style.css
index.html

Add Paul's picture and link to portfolio to student showcase

add Paul info and pic

---

index.html

Photo added for real this time.

Add photo for real

---

README.md
package-lock.json

Add Melissa to contributor list

added Melissa to contributors list

---

README.md
package-lock.json

Add My Name, Please.

---

README.md
package-lock.json

adding contibutor name

---

css/style.css
index.html

Styles Added

---

css/style.css

Unsure just what I was thinking :-(

Rethinking Poor Choice of CSS Selector

---

index.html

IMG style happy fix

---

css/style.css

Seeing BLUE

---

README.md

Student showcase

---

README.md
index.html

i did a thing

---

README.md

Please add me, I need the fame

added Danielle Snyder to contributor list!

---

index.html

Please Add My Info!!! Thanks Alex.

Added Martins Info to Div Six

---

index.html

Please add my profile to box 2.  Thanks!

Add profile

---

index.html

add number 9 profile

---

index.html

My handsome pic, link, and name paaaaaaaa-lease!

added to 3 box

---

README.md

Add Janae C. Johnson to contributors list

---

index.html
theme/style.css

Beautified Grid

---

index.html
theme/style.css

Please add my pull request Alex, I updated my styles! Thanks!

Created responsive styles for Martins Div

---

index.html
theme/style.css

I had to redo my work. Please add. Thanks.

box 2 content 

---

index.html
theme/style.css

Add stuff to FOURTEEN div for Janae

---

index.html
theme/style.css

add background color and picture to box 7

---

theme/style.css

Please add my pull request, I updated my text styles. Thanks!

Created text styles for MartinsDiv using css selectors

---

index.html
theme/style.css

I think my background color will work and look super cute now.

Add background color to Janae div

---

index.html

add my blue photo to #9 

---

index.html
theme/style.css

Change background

---

index.html
theme/style.css

add photo 100

---

index.html
theme/style.css

color bdiv

---

index.html

updated link to my profile 

---

index.html
theme/style.css

changed photo

---

index.html
theme/style.css

Add changes to Meagan's student showcase box

---

index.html

Thanks for your patience, great teaching skills and just for being so awesome to let me change my link!

Changed my link to point to my portfolio.

---

README.md

Marquis Patton Pull Request

---

README.md

Add to the contributors List

---

README.md

added name to readme.md

---

index.html
theme/style.css

delete . before theme, added link stylesheet code back

delete period before theme

---

index.html

updated profile pic

---

index.html
theme/style.css

delete text dec color for cece h3

delete text dec color

---

README.md

Hi Alex, I'd like to add my name to the collaborators on this project so I can get credit without doing any actual work :P

Add collaborator Drew Roby

---

README.md

Hello, I'm going to add my name. Have a good day.

Jennifer Fisher

---

README.md

Adding my name for the student-showcase

newrepository

---

README.md

I would like to add my name to your project

Tyler Krszjzaniek

---

README.md

first of many messages to come

Adding name to your Repo

---

README.md

showcase commit

---

README.md

Ashlea Swindell

---

index.html

Hello,
I would like to add my contact information to the project. 
Thank you.

Add grid content request

---

index.html

add picture and links

---

index.html
theme/style.css

Please accept my changes to my code!
Thanks!
-Sidney

margin changes to text

---

README.md

This added my awesome name Omar Helal.

Add Omar Helal to contributers list

---

README.md

Eric Humphrey student showcase

---

README.md

You should add me to the code yep . . .   :) 👍

Hello it's Arey

---

README.md

Collaboration time, added student showcase

---

README.md

Accept this so I can contribute to the class... please. 💯

Add Kayode Idris Jr to contributors list

---

README.md

 Add Siddhi Goswami to contributors list

---

README.md

STUDENT-SHOWCASE!!! 
*AIR HORNS*
Lets git it fam.
please accept my changes to the README.md to add "Adam Ladd" as a contributor

Add Adam Ladd to contributors list

---

README.md

this is for the  leader of the blessed savvy covers free world. :)

+Menishia Holden-Savvy Coders Student Showcase

---

README.md

Marcus Boyd Showcase

---

README.md

Please accept my pull request.

Luke Siecinski

---

index.html

I have updated Number four per instructions. - Omar Helal

Student Showcase Number 4

---

index.html

Please allow my changes to be made to the benevolent directory.

Added pic, name, quote, and contact info

---

index.html

A brief introduction of a future coding rockstar = D

add personal profile in the #9 slot 

---

index.html

added my info

---

index.html

Here is what Div 11 looks like so far

Div 11 for showcase

---

index.html
theme/lib/grid.css

Simple styling change to grid.css and indentation edit on html

Simple styling change to grid.css and indentation edit on html

---

index.html

Added my changes, number 2

---

index.html

added my info & quote

---

README.md

Add Jim Guccione to Collaborators

---

README.md

Please kind sir, would you add this to the master?

Added self! :rainbow:

---

README.md

Travis Dellard added

---

README.md

Accept my pull Rrequest oh Great One

---

README.md

Dan Catanzaro

---

README.md

Updated the collaborators list

collaborator List

---

README.md

Kelsey Sikes

---

README.md

Chad in name only wants to be added homey.

please add chad to group, said sam i am in his coupe.

---

README.md

Student show case

---

index.html

Info updated. Can you please add?

Kelsey Sikes - Updated Info 

---

index.html

I have added my initial content. Please review.

Nick M. initial content

---

index.html

do this thing please and thank you maybe? 🗡 wow cool there is a dagger emoji wtf

Added details about self

---

index.html

my html code 1

---

index.html
theme/style.css

please sir, may i have some [pull request]?

---

index.html
theme/style.css

more style changes :cloud:

---

README.md

Adding Derek to the contributor list!

Add name to contributor list in README.md

---

README.md

Please let me PULLLLLLLL so I can add my name?

add Phill Temple name

---

README.md

Fabiane Clubb- added my name to the ReadMe.md

Add name to ReadMe.md

---

README.md

: sparkless Add Summer to contributer list

---

README.md

:congratulations: joe asaro contributer

---

README.md

ModShowcase

---

README.md

please adopt changes into your repository

please adopt changes into your repository

---

README.md

Would you kindly add me muwahahahaha!

modified showcase

---

README.md

Adding Kayla Forsythe to the contributors

Add Kayla Forsythe

---

index.html

Added some items to div thirteen, yes i know i still need an actual photo of me

Add content to div thirteen

---

index.html

summers hotwings

---

index.html

please include my sicko html codes. sir 🤠

❏ div html

---

index.html
theme/style.css

Add #derek styling to #derek content (:sparkles::rainbow::sparkles:

---

README.md

Hey man, can you merge this because you are so cool? 🦄

✨ Add name to contributers' list

---

README.md

added my name because I contributed.

Could you add me to the list of changes, my guy?

---

README.md

h3y d06 c4n y0u 4dd my n4m3 70 7h47 7h1n6?

AddedNameToREADME

---

README.md

Please add my changes cool instructor!
-Stephen

Pull Request ReadMe

---

README.md

added name like juan

---

README.md

Can you please add me to contributors?

added name to contributors.

---

README.md

:sparkles: added Amanda to contributor's list

---

README.md

Actually added nathaniel to contribute

---

index.html

:art: Added my info to Line

---

index.html

AddedBioInfo

---

index.html

added my own code to group project

---

index.html

Please approve cool instructor

Added Image and Contact Information

---

index.html

Added Amanda's intro

---

index.html

eyyyy lmao made some changes :insertalexemojihere:

added basic info to index.html

---

index.html

Can you allow the pull please?

added personal information to list.

---

index.html

Its my intro

---

index.html
theme/style.css

Can you please accept my pull?

changed font color

---

theme/style.css

added some alignment

---

index.html
theme/style.css

Made style id

---

README.md

Hey , May you please merge my work. Its very important information that must be seen.
Knowledge is power.

ElClassaWithAlexinto

---

README.md

Oh great and munificent dictator, please accept this pull request from me, your humble servant.

:tada: Added Quinn to list of contributors

---

README.md

Hello Alex, B.D.
Por favor merge my pull request.
Kayla

:sparkles: add Kayla to list of contributors

---

index.html

hey, look at this really great thing i did!

:sparkles: Added some Quinnformation to my div

---

index.html

followed the rules

---

index.html

Patch on the Savvy Coders Quilt
